<?php

namespace ContainerPQXAhh6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__3TUv5DService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..3TUv5D' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..3TUv5D'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'projetRepository' => ['privates', 'App\\Repository\\ProjetRepository', 'getProjetRepositoryService', true],
        ], [
            'em' => '?',
            'projetRepository' => 'App\\Repository\\ProjetRepository',
        ]);
    }
}
