<?php

namespace ContainerPQXAhh6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Kw5kbo9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kw5kbo9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kw5kbo9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'recompense' => ['privates', '.errored..service_locator.kw5kbo9.App\\Entity\\Recompense', NULL, 'Cannot autowire service ".service_locator.kw5kbo9": it needs an instance of "App\\Entity\\Recompense" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'recompense' => 'App\\Entity\\Recompense',
        ]);
    }
}
