<?php

namespace ContainerPQXAhh6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGeminiServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\GeminiService' shared autowired service.
     *
     * @return \App\Service\GeminiService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'GeminiService.php';

        return $container->privates['App\\Service\\GeminiService'] = new \App\Service\GeminiService($container->getEnv('GOOGLE_APPLICATION_CREDENTIALS'), $container->getEnv('GEMINI_API_ENDPOINT'), 'projects/valiant-azimuth-402115/locations/us-central1/publishers/google/models/gemini-pro', ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
