categories:
  - Information Request
  - Technical Support
  - HR Inquiry
  - Announcement
  - Feedback & Suggestions
  - Document Request
  - Training & Development
  - Meeting Request
  - Policy Clarification
  - Facilities Issue
  - Project Collaboration
  - General Discussion
  - Job Posting/Internal Mobility
  - Event Participation
  - Lost and Found