<?php

namespace ContainerXr1CRP0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Mcb0AeZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mcb0AeZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mcb0AeZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'recompenseRepository' => ['privates', 'App\\Repository\\RecompenseRepository', 'getRecompenseRepositoryService', true],
        ], [
            'em' => '?',
            'recompenseRepository' => 'App\\Repository\\RecompenseRepository',
        ]);
    }
}
