<?php

namespace ContainerXr1CRP0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BBZTkT8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BBZTkT8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BBZTkT8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chartBuilder' => ['privates', '.errored.Tz.tXRl', NULL, 'Cannot determine controller argument for "App\\Controller\\UserController::profile()": the $chartBuilder argument is type-hinted with the non-existent class or interface: "Symfony\\UX\\Chartjs\\Builder\\ChartBuilderInterface".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'geminiService' => ['privates', 'App\\Service\\GeminiService', 'getGeminiServiceService', true],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'chartBuilder' => '?',
            'entityManager' => '?',
            'geminiService' => 'App\\Service\\GeminiService',
            'validator' => '?',
        ]);
    }
}
