<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDc1zwIy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDc1zwIy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDc1zwIy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDc1zwIy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDc1zwIy\App_KernelDevDebugContainer([
    'container.build_hash' => 'Dc1zwIy',
    'container.build_id' => '20108314',
    'container.build_time' => 1746360906,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDc1zwIy');
