<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPQXAhh6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPQXAhh6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPQXAhh6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPQXAhh6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPQXAhh6\App_KernelDevDebugContainer([
    'container.build_hash' => 'PQXAhh6',
    'container.build_id' => '54e25d0b',
    'container.build_time' => 1746315976,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPQXAhh6');
