symfonycasts_reset_password:
    # Replace symfonycasts.reset_password.fake_request_repository with the full
    # namespace of the password reset request repository after it has been created.
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    enable_garbage_collection: true


