<?php

namespace ContainerDc1zwIy;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P1qxq46Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.P1qxq46' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.P1qxq46'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'programmebienetre' => ['privates', '.errored..service_locator.P1qxq46.App\\Entity\\Programmebienetre', NULL, 'Cannot autowire service ".service_locator.P1qxq46": it needs an instance of "App\\Entity\\Programmebienetre" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'programmebienetre' => 'App\\Entity\\Programmebienetre',
        ]);
    }
}
