<?php

namespace ContainerDc1zwIy;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MGZ1HGjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mGZ1HGj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mGZ1HGj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'avis' => ['privates', '.errored..service_locator.mGZ1HGj.App\\Entity\\Avis', NULL, 'Cannot autowire service ".service_locator.mGZ1HGj": it needs an instance of "App\\Entity\\Avis" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'programmebienetreRepository' => ['privates', 'App\\Repository\\ProgrammebienetreRepository', 'getProgrammebienetreRepositoryService', true],
        ], [
            'avis' => 'App\\Entity\\Avis',
            'entityManager' => '?',
            'programmebienetreRepository' => 'App\\Repository\\ProgrammebienetreRepository',
        ]);
    }
}
