<?php

namespace ContainerUGR65Vs;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CPtdf4kService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CPtdf4k' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CPtdf4k'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'quizRepository' => ['privates', 'App\\Repository\\QuizRepository', 'getQuizRepositoryService', true],
            'scoreRepository' => ['privates', 'App\\Repository\\ScoreRepository', 'getScoreRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'entityManager' => '?',
            'paginator' => '?',
            'quizRepository' => 'App\\Repository\\QuizRepository',
            'scoreRepository' => 'App\\Repository\\ScoreRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
