<?php

namespace ContainerUGR65Vs;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Yfxol_4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yfxol.4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yfxol.4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'programmebienetreRepository' => ['privates', 'App\\Repository\\ProgrammebienetreRepository', 'getProgrammebienetreRepositoryService', true],
        ], [
            'em' => '?',
            'programmebienetreRepository' => 'App\\Repository\\ProgrammebienetreRepository',
        ]);
    }
}
