<?php

namespace ContainerUGR65Vs;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecompenseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.61idZAZ.App\Entity\Recompense' shared service.
     *
     * @return \App\Entity\Recompense
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.61idZAZ": it needs an instance of "App\\Entity\\Recompense" but this type has been excluded in "config/services.yaml".');
    }
}
