<?php

namespace ContainerETXdQkI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProgrammebienetreService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.P1qxq46.App\Entity\Programmebienetre' shared service.
     *
     * @return \App\Entity\Programmebienetre
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.P1qxq46": it needs an instance of "App\\Entity\\Programmebienetre" but this type has been excluded in "config/services.yaml".');
    }
}
